components:
  schemas:
    Pet:
      type: object
      properties:
        name:
          description: Nombre de la mascota
          type: string
        specie:
          description: Especie animal de la mascota
          type: string
        birthDate:
          description: Fecha estimada de nacimiento
          type: date
        adopted:
          description: Indicador de si la mascota fue adoptada
          type: boolean
        owner:
          description: ObjectId que referencia al usuario que adoptó la mascota
          type: string
        image:
          description: Foto de la mascota
          type: string
      example:
        name: Igna
        specie: Conejo
        birthDate: 09-07-2020
        adopted: false
        image: https://upload.wikimedia.org/wikipedia/commons/3/37/Oryctolagus_cuniculus_Tasmania_2.jpg
    PetUpdate:
      type: object
      properties:
        name:
          description: Nombre de la mascota
          type: string
        specie:
          description: Especie animal de la mascota
          type: string
        birthDate:
          description: Fecha estimada de nacimiento
          type: date
        adopted:
          description: Indicador de si la mascota fue adoptada
          type: boolean
        owner:
          description: ObjectId que referencia al usuario que adoptó la mascota
          type: string
        image:
          description: Foto de la mascota
          type: string
      example:
        name: Gabriela
  responses:
    create:
      type: object
      properties:
        status: Indicador del estado de la respuesta
        payload: Documento de mascota creado correctamente
      example:
        status: success
        payload:
          _id: 6541aae1e7b2683607f2b4df
          name: Igna
          specie: Conejo
          birthDate: 09-07-2020
          adopted: false
          image: https://upload.wikimedia.org/wikipedia/commons/3/37/Oryctolagus_cuniculus_Tasmania_2.jpg
    read:
      type: object
      properties:
        status: Indicador del estado de la respuesta
        payload: Devuelve los documentos de mascotas del servidor
      example:
        status: success
        payload:
          - _id: 6541aae1e7b2683607f2b4df
            name: Igna
            specie: Conejo
            birthDate: 09-07-2020
            adopted: false
            image: https://upload.wikimedia.org/wikipedia/commons/3/37/Oryctolagus_cuniculus_Tasmania_2.jpg
          - _id: 6541aae1e7b2683607f2b4de
            name: Emiliano
            specie: Conejo
            birthDate: 09-07-2020
            adopted: false
            image: https://upload.wikimedia.org/wikipedia/commons/3/37/Oryctolagus_cuniculus_Tasmania_2.jpg
          - _id: 6541aae1e7b2683607f2b4da
            name: Saul
            specie: Conejo
            birthDate: 09-07-2020
            adopted: false
            image: https://upload.wikimedia.org/wikipedia/commons/3/37/Oryctolagus_cuniculus_Tasmania_2.jpg
    update:
      type: object
      properties:
        status:
          type: string
          description: Indicador del estado de la respuesta
        payload:
          type: string
          description: ObjectId del documento modificado
      example:
          status: success
          payload: 6541aae1e7b2683607f2b4da
    auth:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: auth
        from: POST /api/sessions/signout middleware
        message: Invalid credentials
    forbidden:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: forbidden
        from: POST /api/sessions/signout middleware
        message: Not Allowed
    incomplete:
      type: object
      properties:
        status:
          type: string
          description: Estado de la solicitud
        from:
          type: string
          description: Descripción del endpoint del error
        message:
          type: string
          description: Descripción del error
      example:
        status: error
        from: POST /api/sessions/register middleware
        message: Incomplete values
    notFound:
      type: object
      properties:
        status:
          type: string
          description: Indicador del estado de la respuesta
        from:
          type: string
          description: Indicador de dónde se cometió el error
        message:
          type: string
          description: Indicador de qué error se cometió
      example:
        status: error
        from: controller
        message: Not found documents
    fatal:
      type: object
      properties:
        status:
          type: string
          description: Indicador del estado de la respuesta
        from:
          type: string
          description: Indicador de dónde se cometió el error
        message:
          type: string
          description: Indicador de qué error se cometió
      example:
        status: fatal
        from: error handler
        message: dat is not defined
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
paths:
  /api/pets:
    post:
      summary: Agregar una nueva mascota al sistema de adopción de mascotas
      tags:
        - Pet
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Pet'
      responses:
        "201":
          description: Éxito en la carga de una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/create'
        "401":
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#components/responses/auth'
        "403":
          description: Acceso no permitido
          content:
            application/json:
              schema:
                $ref: '#components/responses/forbidden'
        "500":
          description: Falla del servidor al crear una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/fatal'
    get:
      summary: Leer las mascotas del sistema
      tags:
        - Pet
      parameters:
        - name: page
          in: query
          type: integer
          description: Numero de página a mostrar
        - name: limit
          in: query
          type: integer
          description: Numero de documentos a mostrar por página
      responses:
        "200":
          description: Éxito en la lectura de mascotas
          content:
            application/json:
              schema:
                $ref: '#components/responses/read'
        "404":
          description: Documento/s no encontrados
          content:
            application/json:
              schema:
                $ref: '#components/responses/notFound'
        "500":
          description: Falla del servidor al leer las mascotas
          content:
            application/json:
              schema:
                $ref: '#components/responses/fatal'
  /api/pets/{pid}:
    put:
      summary: Actualizar los datos de una mascota
      tags:
        - Pet
      security:
        - cookieAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: ObjectId de la mascota a modificar
          schema:
            $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/PetUpdate'
      responses:
        "200":
          description: Éxito al actualizar una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/update'
        "401":
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#components/responses/auth'
        "403":
          description: Acceso no permitido
          content:
            application/json:
              schema:
                $ref: '#components/responses/forbidden'
        "404":
          description: Documento/s no encontrados
          content:
            application/json:
              schema:
                $ref: '#components/responses/notFound'
        "500":
          description: Falla del servidor al actualizar una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/fatal'
    delete:
      summary: Eliminar una mascota del sistema
      tags:
        - Pet
      security:
        - cookieAuth: []
      parameters:
        - name: pid
          in: path
          required: true
          description: ObjectId de la mascota a eliminar
          schema:
            $type: string
      responses:
        "200":
          description: Éxito al eliminar una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/update'
        "400":
          description: Campos faltantes
          content:
            application/json:
              schema:
                $ref: '#components/responses/incomplete'
        "401":
          description: Credenciales invalidas
          content:
            application/json:
              schema:
                $ref: '#components/responses/auth'
        "403":
          description: Acceso no permitido
          content:
            application/json:
              schema:
                $ref: '#components/responses/forbidden'
        "404":
          description: Documento/s no encontrados
          content:
            application/json:
              schema:
                $ref: '#components/responses/notFound'
        "500":
          description: Falla del servidor al actualizar una mascota
          content:
            application/json:
              schema:
                $ref: '#components/responses/fatal'